[development]
address = "localhost"
port = 7000
workers = 10
keep_alive = 5
log = "normal"
secret_key = "I3RxytL+PrVLIKcuem5gdHBl/FDL4GufWyhGNh3WDiM="
limits = { forms = 32768 }
_url_default = ""
limit_timeout = 1000 # ms
default_source = ""
vietbando_api_key = ""
vietbando_url = "http://developers.vietbando.com/V2/service/PartnerPortalService.svc/rest/ViaRoute"
google_url = "https://maps.googleapis.com/maps/api/directions/json"
google_api_key = ""

[staging]
address = "127.0.0.1"
port = 7000
workers = 10
keep_alive = 5
log = "normal"
secret_key = "k443thezEGLrJK6HQ5cUim0cFCGbOkDcUWCEgGlwhS4="
limits = { forms = 32768 }
_url_default = ""
limit_timeout = 300 # ms
default_source = ""
vietbando_api_key = ""
vietbando_url = "http://developers.vietbando.com/V2/service/PartnerPortalService.svc/rest/ViaRoute"
google_url = "https://maps.googleapis.com/maps/api/directions/json"
google_api_key = ""

[production]
address = "0.0.0.0"
port = 8000
workers = 10
keep_alive = 5
log = "critical"
secret_key = "jnfgAN2NhORuIWLhCcikKhjwcuOCSd87funBphuoKxk="
limits = { forms = 32768 }
_url_default = ""
limit_timeout = 300 # ms
default_source = ""
vietbando_api_key = ""
vietbando_url = "http://developers.vietbando.com/V2/service/PartnerPortalService.svc/rest/ViaRoute"
google_url = "https://maps.googleapis.com/maps/api/directions/json"
google_api_key = ""